# Generated by Django 5.2.5 on 2025-08-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_chefs_alter_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefs',
            name='address',
        ),
        migrations.RemoveField(
            model_name='chefs',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chefs',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='chefs',
            name='year',
        ),
        migrations.AddField(
            model_name='chefs',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chefs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='chefs',
            name='ins_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chefs',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chefs',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
