# Generated by Django 5.2.5 on 2025-09-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0004_remove_chefs_address_remove_chefs_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='chefs',
            name='ins_link',
        ),
        migrations.AlterField(
            model_name='chefs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='res/food/images/'),
        ),
    ]
